services:
  ai-api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mind2-ai-api:dev
    volumes:
      - ./storage:/data/storage
      - ./inbox:/data/inbox
      - G:\Dropbox\MINDUPLOAD:/data/upload
    environment:
      - PYTHONPATH=/app
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - LOG_LEVEL=${LOG_LEVEL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - STORAGE_DIR=/data/storage
      - FTP_LOCAL_DIR=/data/inbox
      - FTP_HOST=${FTP_HOST}
      - FTP_PORT=${FTP_PORT}
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - FTP_REMOTE_DIR=${FTP_REMOTE_DIR}
      - FTP_LOCAL_MOVE_DIR=${FTP_LOCAL_MOVE_DIR}
      - FTP_TLS=${FTP_TLS}
      - FTP_PASSIVE=${FTP_PASSIVE}
      - FTP_ALLOWED_EXT=${FTP_ALLOWED_EXT}
      - FTP_DELETE_AFTER=${FTP_DELETE_AFTER}
      - DB_AUTO_MIGRATE=0
    depends_on:
      mysql:
        condition: service_healthy
    networks: [main]
    profiles: [main]

  celery-worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mind2-ai-api:dev # Use the same image as the api
    command: ["celery", "-A", "services.tasks.celery_app", "worker", "-Q", "default", "-n", "default@%h", "--loglevel=INFO", "--concurrency=2", "--soft-time-limit=1800", "--time-limit=1900"]
    entrypoint: []
    volumes:
      - ./storage:/data/storage
      - G:\Dropbox\MINDUPLOAD:/data/upload
    environment:
      - PYTHONPATH=/app
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STORAGE_DIR=/data/storage
      - ENABLE_REAL_OCR=${ENABLE_REAL_OCR}
      - OCR_LANG=${OCR_LANG}
      - OCR_USE_ANGLE_CLS=${OCR_USE_ANGLE_CLS}
      - OCR_SHOW_LOG=${OCR_SHOW_LOG}
    depends_on: [redis]
    networks: [main]
    profiles: [main]

  celery-worker-wf1:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mind2-ai-api:dev
    command: ["celery", "-A", "services.tasks.celery_app", "worker", "-Q", "wf1", "-n", "wf1@%h", "--loglevel=INFO", "--concurrency=2", "--soft-time-limit=1800", "--time-limit=1900"]
    entrypoint: []
    volumes:
      - ./storage:/data/storage
      - G:\Dropbox\MINDUPLOAD:/data/upload
    environment:
      - PYTHONPATH=/app
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STORAGE_DIR=/data/storage
      - ENABLE_REAL_OCR=${ENABLE_REAL_OCR}
      - OCR_LANG=${OCR_LANG}
      - OCR_USE_ANGLE_CLS=${OCR_USE_ANGLE_CLS}
      - OCR_SHOW_LOG=${OCR_SHOW_LOG}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on: [redis]
    networks: [main]
    profiles: [main]

  celery-worker-wf2:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mind2-ai-api:dev
    command: ["celery", "-A", "services.tasks.celery_app", "worker", "-Q", "wf2", "-n", "wf2@%h", "--loglevel=INFO", "--concurrency=2", "--soft-time-limit=480", "--time-limit=600"]
    entrypoint: []
    volumes:
      - ./storage:/data/storage
      - G:\Dropbox\MINDUPLOAD:/data/upload
    environment:
      - PYTHONPATH=/app
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STORAGE_DIR=/data/storage
      - ENABLE_REAL_OCR=${ENABLE_REAL_OCR}
      - OCR_LANG=${OCR_LANG}
      - OCR_USE_ANGLE_CLS=${OCR_USE_ANGLE_CLS}
      - OCR_SHOW_LOG=${OCR_SHOW_LOG}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on: [redis]
    networks: [main]
    profiles: [main]

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks: [main]
    profiles: [main]

  mysql:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3310:3306"
    networks: [main]
    profiles: [main]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8087:80"
    depends_on: [mysql]
    networks: [main]
    profiles: [main]

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mobile-capture-frontend:/usr/share/nginx/html/capture:ro
    ports:
      - "8008:80"
    depends_on: [ai-api, mind-web-main-frontend]
    networks: [main]
    profiles: [main]

  mind-web-main-frontend:
    build:
      context: ./main-system/app-frontend
      dockerfile: Dockerfile
      args:
        - VITE_REFRESH_INTERVAL_SECONDS=${VITE_REFRESH_INTERVAL_SECONDS}
    image: mind2-admin-frontend:dev
    depends_on: [ai-api]
    networks: [main]
    profiles: [main]

  mind-web-main-frontend-dev:
    build:
      context: ./main-system/app-frontend
      dockerfile: Dockerfile.dev
    image: mind2-admin-frontend:dev-hotreload
    volumes:
      # Mount source code for hot-reload
      - ./main-system/app-frontend/src:/app/src:ro
      - ./main-system/app-frontend/index.html:/app/index.html:ro
      - ./main-system/app-frontend/vite.config.js:/app/vite.config.js:ro
      # Use named volume for node_modules to avoid platform conflicts
      - mind-frontend-node-modules:/app/node_modules
    environment:
      # Proxy API requests directly to backend service (not through nginx)
      - VITE_API_PROXY_TARGET=http://ai-api:5000
      - VITE_REFRESH_INTERVAL_SECONDS=${VITE_REFRESH_INTERVAL_SECONDS}
    ports:
      # Expose Vite dev server on host port 5169
      - "5169:5169"
    depends_on: [ai-api]
    networks: [main]
    profiles: [main]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    networks: [main, monitoring]
    profiles: [monitoring]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3003:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    networks: [monitoring]
    profiles: [monitoring]

networks:
  main: {}
  monitoring: {}

volumes:
  mind-frontend-node-modules:
