services:
  ai-api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mind2-ai-api:dev
    volumes:
      - ./storage:/data/storage
      - ./inbox:/data/inbox
    environment:
      - PYTHONPATH=/app
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - LOG_LEVEL=${LOG_LEVEL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - STORAGE_DIR=/data/storage
      - FTP_LOCAL_DIR=/data/inbox
      - FTP_HOST=${FTP_HOST}
      - FTP_PORT=${FTP_PORT}
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - FTP_REMOTE_DIR=${FTP_REMOTE_DIR}
      - FTP_LOCAL_MOVE_DIR=${FTP_LOCAL_MOVE_DIR}
      - FTP_TLS=${FTP_TLS}
      - FTP_PASSIVE=${FTP_PASSIVE}
      - FTP_ALLOWED_EXT=${FTP_ALLOWED_EXT}
      - FTP_DELETE_AFTER=${FTP_DELETE_AFTER}
    networks: [main]
    profiles: [main]

  celery-worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mind2-ai-api:dev # Use the same image as the api
    command: ["celery", "-A", "services.tasks.celery_app", "worker", "--loglevel=INFO"]
    environment:
      - PYTHONPATH=/app
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on: [redis]
    networks: [main]
    profiles: [main]

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks: [main]
    profiles: [main]

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3310:3306"
    networks: [main]
    profiles: [main]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8087:80"
    depends_on: [mysql]
    networks: [main]
    profiles: [main]

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mobile-capture-frontend:/usr/share/nginx/html/capture:ro
    ports:
      - "8008:80"
    depends_on: [ai-api, mind-web-main-frontend]
    networks: [main]
    profiles: [main]

  mind-web-main-frontend:
    build:
      context: .
      dockerfile: ./main-system/app-frontend/Dockerfile
    image: mind2-admin-frontend:dev
    depends_on: [ai-api]
    networks: [main]
    profiles: [main]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    networks: [main, monitoring]
    profiles: [monitoring]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3003:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    networks: [monitoring]
    profiles: [monitoring]

networks:
  main: {}
  monitoring: {}