openapi: 3.0.0
info:
  title: FirstCard Reconciliation API
  version: 0.1.0
servers:
  - url: /ai/api
    description: MIND v2.0 API base
paths:
  /reconciliation/firstcard/import:
    post:
      summary: Import FirstCard invoice
      responses:
        '200': { description: OK }
  /reconciliation/firstcard/match:
    post:
      summary: Match invoice lines to receipts
      responses:
        '200': { description: OK }
  /reconciliation/firstcard/statements:
    get:
      summary: List statements
      responses:
        '200': { description: OK }
  /reconciliation/firstcard/statements/{id}/confirm:
    post:
      summary: Confirm match
      responses:
        '200': { description: OK }
  /reconciliation/firstcard/statements/{id}/reject:
    post:
      summary: Reject match
      responses:
        '200': { description: OK }
