from __future__ import annotations

from .common import celery_app
from .history import INSERT_HISTORY_SQL, _history
from .file_management_tasks import (
    _collect_text_hints,
    _enqueue_invoice_document,
    _enforce_file_metadata,
    _get_file_type,
    _load_accounting_inputs,
    _load_ai_context,
    _load_receipt_items,
    _load_receipt_model,
    _maybe_advance_invoice_from_file,
    _move_to_manual_review,
    _save_accounting_entries,
    _update_file_fields,
    _update_file_status,
)
from .invoice_tasks import (
    _format_date_for_db,
    _persist_creditcard_invoice_items,
    _persist_creditcard_invoice_main,
    _persist_creditcard_invoice_ocr,
    _persist_invoice_lines,
    _to_decimal,
    process_invoice_document,
)
from .creditcard_tasks import (
    _ensure_creditcard_pages_and_ocr,
    _load_credit_items_for_invoice,
    _select_credit_item_for_line,
    auto_match_invoice_lines,
    refresh_invoice_match_state,
)
from .ai_pipeline_tasks import (
    UnsupportedDocumentTypeError,
    _infer_document_type,
    _load_rules,
    _run_ai_pipeline,
    _rules_file,
)
from .utils.invoice_utils import (
    _collect_invoice_ocr_text,
    _get_invoice_parent_id,
    _invoice_page_progress,
    _load_invoice_file_records,
    _load_invoice_metadata,
    _load_unified_file_info,
    _set_invoice_metadata_field,
    _update_invoice_metadata,
)
from .workflow_base import (
    _log_import_stage,
    begin_import_stage,
    complete_import_stage,
    ensure_workflow,
    get_workflow_run,
    get_workflow_stage,
    log_finalize_failure,
    log_import_decision,
    log_import_event,
    mark_stage,
)
from .ocr_tasks import (
    wf1_run_ocr,
    wf2_merge_ocr_results,
    wf2_prepare_pdf_pages,
    wf2_run_invoice_analysis,
    wf2_run_page_ocr,
)
from .workflow_tasks import (
    dispatch_workflow,
    wf1_finalize,
    wf1_run_ai_pipeline,
    wf2_finalize,
    wf3_firstcard_invoice,
)

__all__ = [
    "celery_app",
    "INSERT_HISTORY_SQL",
    "_history",
    "_update_file_status",
    "_update_file_fields",
    "_enforce_file_metadata",
    "_enqueue_invoice_document",
    "_move_to_manual_review",
    "_maybe_advance_invoice_from_file",
    "_load_receipt_model",
    "_get_file_type",
    "_collect_text_hints",
    "_load_ai_context",
    "_load_accounting_inputs",
    "_load_receipt_items",
    "_save_accounting_entries",
    "_load_unified_file_info",
    "_get_invoice_parent_id",
    "_load_invoice_metadata",
    "_update_invoice_metadata",
    "_set_invoice_metadata_field",
    "_invoice_page_progress",
    "_load_invoice_file_records",
    "_collect_invoice_ocr_text",
    "process_invoice_document",
    "_persist_invoice_lines",
    "_to_decimal",
    "_format_date_for_db",
    "_persist_creditcard_invoice_ocr",
    "_persist_creditcard_invoice_main",
    "_persist_creditcard_invoice_items",
    "_ensure_creditcard_pages_and_ocr",
    "_load_credit_items_for_invoice",
    "_select_credit_item_for_line",
    "auto_match_invoice_lines",
    "refresh_invoice_match_state",
    "UnsupportedDocumentTypeError",
    "_run_ai_pipeline",
    "_infer_document_type",
    "_rules_file",
    "_load_rules",
    "get_workflow_run",
    "get_workflow_stage",
    "ensure_workflow",
    "mark_stage",
    "_log_import_stage",
    "begin_import_stage",
    "complete_import_stage",
    "log_import_decision",
    "log_import_event",
    "log_finalize_failure",
    "dispatch_workflow",
    "wf1_run_ocr",
    "wf1_run_ai_pipeline",
    "wf1_finalize",
    "wf2_prepare_pdf_pages",
    "wf2_run_page_ocr",
    "wf2_merge_ocr_results",
    "wf2_run_invoice_analysis",
    "wf2_finalize",
    "wf3_firstcard_invoice",
]
