from __future__ import annotations

from services.invoice_status import transition_document_status, transition_processing_status
from services.ocr import run_ocr

from .base import celery_app, db_cursor, logger
from .history import INSERT_HISTORY_SQL, _history
from .utils.metadata_utils import (
    _enforce_file_metadata,
    _get_file_type,
    _get_invoice_parent_id,
    _load_unified_file_info,
    _update_file_fields,
)
from .utils.invoice_utils import (
    _collect_invoice_ocr_text,
    _invoice_page_progress,
    _load_invoice_file_records,
    _load_invoice_metadata,
    _set_invoice_metadata_field,
    _update_invoice_metadata,
)
from .utils.status_utils import (
    _enqueue_invoice_document,
    _maybe_advance_invoice_from_file,
    _update_file_status,
)
from .utils.value_utils import _format_date_for_db, _to_decimal
from .invoice_tasks import process_invoice_document, _persist_invoice_lines
from .creditcard_tasks import (
    _ensure_creditcard_pages_and_ocr,
    _load_credit_items_for_invoice,
    _persist_creditcard_invoice_items,
    _persist_creditcard_invoice_main,
    _persist_creditcard_invoice_ocr,
    _select_credit_item_for_line,
    auto_match_invoice_lines,
    refresh_invoice_match_state,
    wf3_firstcard_invoice,
)
from .ai_pipeline_tasks import (
    UnsupportedDocumentTypeError,
    _collect_text_hints,
    _infer_document_type,
    _load_accounting_inputs,
    _load_ai_context,
    _load_receipt_items,
    _load_receipt_model,
    _load_rules,
    _move_to_manual_review,
    _run_ai_pipeline,
    _rules_file,
    _save_accounting_entries,
)
from .file_management_tasks import (
    _log_import_stage,
    begin_import_stage,
    complete_import_stage,
    dispatch_workflow,
    ensure_workflow,
    get_workflow_run,
    get_workflow_stage,
    log_finalize_failure,
    log_import_decision,
    log_import_event,
    mark_stage,
)
from .ocr_tasks import (
    wf1_finalize,
    wf1_run_ai_pipeline,
    wf1_run_ocr,
    wf2_finalize,
    wf2_merge_ocr_results,
    wf2_prepare_pdf_pages,
    wf2_run_invoice_analysis,
    wf2_run_page_ocr,
)
from .legacy import (
    _fail_invoice_processing,
    _enqueue_invoice_ai_extraction,
    process_ai_pipeline,
    process_invoice_ai_extraction,
    process_ocr,
)

__all__ = [
    'celery_app',
    'db_cursor',
    'logger',
    'INSERT_HISTORY_SQL',
    '_history',
    '_enforce_file_metadata',
    '_get_file_type',
    '_get_invoice_parent_id',
    '_load_unified_file_info',
    '_update_file_fields',
    '_collect_invoice_ocr_text',
    '_invoice_page_progress',
    '_load_invoice_file_records',
    '_load_invoice_metadata',
    '_set_invoice_metadata_field',
    '_update_invoice_metadata',
    '_enqueue_invoice_document',
    '_maybe_advance_invoice_from_file',
    '_update_file_status',
    '_format_date_for_db',
    '_to_decimal',
    'process_invoice_document',
    '_persist_invoice_lines',
    '_ensure_creditcard_pages_and_ocr',
    '_load_credit_items_for_invoice',
    '_persist_creditcard_invoice_items',
    '_persist_creditcard_invoice_main',
    '_persist_creditcard_invoice_ocr',
    '_select_credit_item_for_line',
    'auto_match_invoice_lines',
    'refresh_invoice_match_state',
    'wf3_firstcard_invoice',
    'UnsupportedDocumentTypeError',
    '_collect_text_hints',
    '_infer_document_type',
    '_load_accounting_inputs',
    '_load_ai_context',
    '_load_receipt_items',
    '_load_receipt_model',
    '_load_rules',
    '_move_to_manual_review',
    '_run_ai_pipeline',
    '_rules_file',
    '_save_accounting_entries',
    '_log_import_stage',
    'begin_import_stage',
    'complete_import_stage',
    'dispatch_workflow',
    'ensure_workflow',
    'get_workflow_run',
    'get_workflow_stage',
    'log_finalize_failure',
    'log_import_decision',
    'log_import_event',
    'mark_stage',
    'wf1_finalize',
    'wf1_run_ai_pipeline',
    'wf1_run_ocr',
    'wf2_finalize',
    'wf2_merge_ocr_results',
    'wf2_prepare_pdf_pages',
    'wf2_run_invoice_analysis',
    'wf2_run_page_ocr',
    'process_ocr',
    'process_ai_pipeline',
    'process_invoice_ai_extraction',
    '_fail_invoice_processing',
    '_enqueue_invoice_ai_extraction',
    'transition_processing_status',
    'transition_document_status',
    'run_ocr',
]
